### PR TITLE
Add `live` column to indicate whether or not a fundraiser has gone live.

### PR DESCRIPTION
**Pull request by thaumasiotes**
This should implement issue #40. It adds a boolean `live` column to the fundraisers table, the API implementation automatically picks that up, and the artisanally hand-crafted migration will work on an existing, data-filled database.

I want to flag that the migrations Alembic generates are given random names and then linked to each other, by name, within the migration scripts. Like this:

```Python
# revision identifiers, used by Alembic.
revision = 'c58942fe6b16'
down_revision = '22bb36ffc124'
branch_labels = None
depends_on = None
```

What that means is that, if two pull requests both include new migrations, there will not be a git conflict, as the two new migrations both create new files. But there **will be** a conflict in the migrations themselves, because the two new migrations will both claim to follow the same previous database state, and upgrading from that state will become ill-defined.

### CODE REVIEW

**Review by rraihansaputra — APPROVED** [review]

**Comment by rraihansaputra** [comment]
I've looked over the changes. This PR is strictly adding the column. You're working on the endpoints to change the `live` status, right?

**Comment by thaumasiotes** [comment]
Actually, that's a good point. The existing endpoint should automatically include the new `live` column -- but that's not really what we want. It would probably be better to have the endpoint filter non-live fundraisers on the server side and return only live ones.

**Comment by rraihansaputra** [comment]
I think there are several functionalities from the backend for this card:
- Filter the `/fundraisers` response to only include live ones as you have mentioned above
- Restrict access non-live fundraiser so it can only be seen by the creator
- Modify/Update the fundraiser's live field, only by the creator

The endpoint will include the `live` column, I don't think that is a problem. But inactive fundraisers should not be seen on the public `/fundraisers` list.

**Comment by thaumasiotes** [comment]
> - Modify/Update the fundraiser's live field, only by the creator

It looks to me like modifying any aspect of the fundraiser already requires you to be the creator:

```Python
class FundraiserResource(Resource):
    @classmethod
    @jwt_required
    def put(cls, fundraiser_id: int):
        user_email = get_jwt_identity()
        user = User.find_by_email(user_email)
        fundraiser = Fundraiser.find_by_id(fundraiser_id)

        if not user:
            return {"message": INVALID_CREDENTIALS}, 401

        if not fundraiser:
            return {"message": FUNDRAISER_NOT_FOUND}, 404

        if user.id != fundraiser.creator_id:
            return {"message": INVALID_CREDENTIALS}, 401
```

**Review by rraihansaputra — APPROVED** [review]

**Comment by rraihansaputra** [comment]
Looks good to me with the constraint that the endpoint for changing the `live` field is accessed through the `PUT /fundraiser/<id>` endpoint.

**Pull request merged**
