### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by aslamm29**
A description of the application with the authors, requirements and steps to start

### CODE REVIEW

**Review by thaumasiotes — COMMENTED** [review]
Seems basically fine. Two thoughts:

1. We've removed `.env` from the repo (because it contains secret values), so its existence here is a conflict.
2. The instructions might want to mention (a) setting up an `.env` file; and (b) installing dependencies from the Pipfile.

**Comment by rraihansaputra** [comment]
echoing Michaels' comment: I have put a README.md on `server/README.md` for setting up and initializing the server. You'll still need to instruct on how to set up the `.env` from `.env.example`

**Comment by rraihansaputra** [comment]
and please rebase the branch from the latest commit from `dev` as I have removed `server/.env` and it's causing the merge conflict.

**Comment by aslamm29** [comment]
Changes made as suggested

**Pull request merged**
